import {
  AlertTriangle,
  Lightbulb,
  Sparkles,
  Target,
  TrendingUp,
} from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { cn } from "@/lib/utils";

type InsightType = "opportunity" | "risk" | "performance" | "action";

interface MockInsight {
  type: InsightType;
  title: string;
  body: string;
}

const MOCK_INSIGHTS: MockInsight[] = [
  {
    type: "performance",
    title: "Basketball exposure is driving returns",
    body: "Basketball cards represent 58% of your portfolio value and account for most of your 1-year gains. Your football holdings are flat by comparison — consider whether you want to rebalance or double down on what's working.",
  },
  {
    type: "risk",
    title: "Concentration in a single player",
    body: "Three of your top five holdings feature the same player across different sets. A pullback in that player's market could disproportionately affect your portfolio. Diversifying across players or sports may reduce single-name risk.",
  },
  {
    type: "opportunity",
    title: "Underperforming lot may be a hold",
    body: "One lot is down 18% vs cost basis, but recent comps for that grade have stabilized. If your thesis hasn't changed, this could be a hold rather than a sell — or a chance to average down if liquidity allows.",
  },
  {
    type: "action",
    title: "Update stale valuations",
    body: "Two held lots haven't had a valuation update in over 90 days. Refreshing current values will improve return accuracy on your dashboard and help surface better buy/sell signals.",
  },
];

const INSIGHT_CONFIG: Record<
  InsightType,
  { icon: React.ReactNode; label: string; className: string }
> = {
  performance: {
    icon: <TrendingUp className="h-4 w-4" />,
    label: "Performance",
    className: "text-primary",
  },
  risk: {
    icon: <AlertTriangle className="h-4 w-4" />,
    label: "Risk",
    className: "text-amber-600 dark:text-amber-400",
  },
  opportunity: {
    icon: <Lightbulb className="h-4 w-4" />,
    label: "Opportunity",
    className: "text-emerald-600 dark:text-emerald-400",
  },
  action: {
    icon: <Target className="h-4 w-4" />,
    label: "Action",
    className: "text-blue-600 dark:text-blue-400",
  },
};

export function PortfolioInsights() {
  return (
    <Card>
      <CardHeader>
        <div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between">
          <div className="flex items-start gap-3">
            <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-primary/10 text-primary">
              <Sparkles className="h-4 w-4" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <CardTitle className="text-base font-medium">
                  Portfolio Insights
                </CardTitle>
                <Badge variant="outline" className="text-[10px]">
                  AI Preview
                </Badge>
              </div>
              <CardDescription className="mt-0.5">
                Personalized observations about your holdings — generated by AI in a
                future release
              </CardDescription>
            </div>
          </div>
        </div>
      </CardHeader>
      <CardContent className="space-y-3">
        <div className="rounded-xl border border-dashed border-primary/25 bg-primary/5 px-3 py-2 text-xs text-muted-foreground">
          Sample insights shown below. These will be tailored to your actual portfolio
          once AI analysis is connected.
        </div>
        <ul className="grid gap-3 sm:grid-cols-2">
          {MOCK_INSIGHTS.map((insight) => {
            const config = INSIGHT_CONFIG[insight.type];
            return (
              <li
                key={insight.title}
                className="rounded-xl border border-border/80 bg-muted/20 p-4"
              >
                <div className="flex items-center gap-2">
                  <span className={cn("shrink-0", config.className)}>
                    {config.icon}
                  </span>
                  <Badge variant="secondary" className="text-[10px]">
                    {config.label}
                  </Badge>
                </div>
                <p className="mt-2 text-sm font-medium leading-snug">
                  {insight.title}
                </p>
                <p className="mt-1.5 text-sm text-muted-foreground leading-relaxed">
                  {insight.body}
                </p>
              </li>
            );
          })}
        </ul>
      </CardContent>
    </Card>
  );
}
